### ISSUE TITLE
Salvare la configurazione

### ISSUE THREAD

**Issue by GiovanniCardamone** [vbextreme/MagixCubic#1]
Sarebbe un'ottima cosa salvare la configurazione fra una partita e l'altra.

Attualmente quando si riapre il gioco viene caricata sempre la configurazione di default.

**Comment by vbextreme** [comment]
work in progress

**Comment by vbextreme** [comment]
Ho aggiunto la funzione per salvare le configurazioni, attendo conferma per chiudere

**Comment by GiovanniCardamone** [comment]
sfortunatamente ho qualche problema ad aggiornare l'easyframework

```
step@Mike:~/workspace/Archive/ubuntu-it/repository/vbextreme/EasyFramework$ sudo ./install
Swipe your finger across the fingerprint reader
--------------------------
- Install Easy Framework -
--------------------------

[OK]easytype
cp ./libeasyalloc.so /usr/lib/libeasyalloc.so
cp ./easyalloc.h /usr/include/easyalloc.h
[OK]easyalloc
cp ./libeasybenchmark.so /usr/lib/libeasybenchmark.so
cp ./easybenchmark.h /usr/include/easybenchmark.h
[OK]easybenchmark
cp ./libeasyconsole.so /usr/lib/libeasyconsole.so
cp ./easyconsole.h /usr/include/easyconsole.h
[OK]easyconsole
cp ./libeasycrypto.so /usr/lib/libeasycrypto.so
cp ./easycrypto.h /usr/include/easycrypto.h
[OK]easycrypto
cp ./libeasyfile.so /usr/lib/libeasyfile.so
cp ./easyfile.h /usr/include/easyfile.h
[OK]easyfile
cp ./libeasylist.so /usr/lib/libeasylist.so
cp ./easylist.h /usr/include/easylist.h
[OK]easylist
cp ./libeasymath.so /usr/lib/libeasymath.so
cp ./easymath.h /usr/include/easymath.h
[OK]easymath
cp ./libeasyserial.so /usr/lib/libeasyserial.so
cp ./easyserial.h /usr/include/easyserial.h
[OK]easyserial
cp ./libeasystring.so /usr/lib/libeasystring.so
cp ./easystring.h /usr/include/easystring.h
[OK]easystring
cp ./libeasythread.so /usr/lib/libeasythread.so
cp ./easythread.h /usr/include/easythread.h
[OK]easythread
make: makefile.auto: File o directory non esistente
make: ***  Nessuna regola per generare l'obiettivo "makefile.auto".  Arresto.
[ER]easyopt
```

come posso risolvere?

**Comment by GiovanniCardamone** [comment]
come non detto, sono riuscito ad aggiornare ed installare anche se non mi fa aggiornare l'easyframework.

tuttavia la configurazione non viene salvata fra un'avvio ed un'altro.

**Comment by vbextreme** [comment]
per il framework posta il problema nella sezione dedicata.
easy framework v0.4 è necessario.

guarderesti nella cartella
~/.config/magixcubic
e posteresti i file presenti?
nel menu ti appare il settaggio del nome?

**Comment by GiovanniCardamone** [comment]
questo e' il filesystem:

```
step@Mike:~/workspace/Archive/ubuntu-it/repository/vbextreme/EasyFramework$ tree.
├── cleanize
├── easyalloc
│   ├── easyalloc.c
│   ├── easyalloc.h
│   ├── easyalloc.man
│   ├── libeasyalloc.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       └── main.o
├── easybenchmark
│   ├── easybenchmark.c
│   ├── easybenchmark.h
│   ├── easybenchmark.man
│   ├── libeasybenchmark.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       └── main.o
├── easyconsole
│   ├── console
│   ├── doc
│   │   └── EasyConsoleReference.odt
│   ├── easyconsole.c
│   ├── easyconsole.h
│   ├── easyconsole.man
│   ├── libeasyconsole.so
│   ├── main.c
│   ├── makefile
│   ├── makefile.auto
│   ├── obj
│   │   ├── easyconsole.o
│   │   └── main.o
│   └── oobj
│       ├── easyconsole.o
│       └── main.o
├── easycrypto
│   ├── easycrypto.c
│   ├── easycrypto.h
│   ├── easycrypto.man
│   ├── libeasycrypto.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── easycrypto.o
│       └── main.o
├── easyfile
│   ├── easyfile.h
│   ├── efile.c
│   ├── libeasyfile.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── efile.o
│       └── main.o
├── easyframework.man
├── easyhttp
│   ├── easyhttp.c
│   ├── easyhttp.h
│   └── main.c
├── easylist
│   ├── easylist.c
│   ├── easylist.h
│   ├── libeasylist.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── easylist.o
│       └── main.o
├── easyman
├── easymarklang
│   ├── easymarklang.c
│   ├── easymarklang.h
│   └── main.c
├── easymath
│   ├── easymath.c
│   ├── easymath.h
│   ├── libeasymath.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── easymath.o
│       └── main.o
├── easymkf
├── easyopt
│   ├── easyopt.c
│   ├── easyopt.h
│   └── main.c
├── easyprocess
│   ├── easyprocess.c
│   ├── easyprocess.h
│   └── main.c
├── easyrequest
├── easyserial
│   ├── easyserial.h
│   ├── libeasyserial.so
│   ├── main.c
│   ├── main.h
│   ├── makefile.auto
│   ├── oobj
│   │   ├── main.o
│   │   └── serfnc.o
│   └── serfnc.c
├── easysocket
│   ├── easysocket.c
│   ├── easysocket.h
│   ├── libeasysocket.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── easysocket.o
│       └── main.o
├── easystatus
├── easystring
│   ├── easystring.c
│   ├── easystring.h
│   ├── libeasystring.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── easystring.o
│       └── main.o
├── easythread
│   ├── easythread.c
│   ├── easythread.h
│   ├── libeasythread.so
│   ├── main.c
│   ├── makefile.auto
│   └── oobj
│       ├── easythread.o
│       └── main.o
├── easytype
│   ├── easytype.h
│   └── easytype.man
├── generate
├── install
├── README.md
└── uninstall
```

**Comment by vbextreme** [comment]
Penso sia più che altro un problema di passaggio dalla vecchia alla nuova versione.
Va in easyframework
$ sudo ./uninstall
$ sudo ./cleanize
controlla che nelle directory siano stati eliminati tutti i file dentro alle cartelle oobj e tutti i makefile.auto, ora riprova:
$ ./generate
$ sudo ./install

se da ancora errore mi servirebbero tutti i messaggi che da "generate"

**Comment by GiovanniCardamone** [comment]
'''
step@Mike:~/workspace/Archive/ubuntu-it/repository/vbextreme/EasyFramework$ sudo ./uninstall 

## [sudo] password for step: 

## \- Uinstall Easy Framework -

[OK]easytype
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easyalloc
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easybenchmark
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easyconsole
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easycrypto
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easyfile
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easylist
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easymath
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easyserial
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easystring
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easythread
make: makefile.auto: File o directory non esistente
make: **\*  Nessuna regola per generare l'obiettivo "makefile.auto".  Arresto.
[OK]easyopt
make: makefile.auto: File o directory non esistente
make: **\*  Nessuna regola per generare l'obiettivo "makefile.auto".  Arresto.
[OK]easymarklang
make: **\*  Nessuna regola per generare l'obiettivo "libuninstall".  Arresto.
[OK]easysocket
make: makefile.auto: File o directory non esistente
make: **\*  Nessuna regola per generare l'obiettivo "makefile.auto".  Arresto.
[OK]easyprocess
make: makefile.auto: File o directory non esistente
make: **\*  Nessuna regola per generare l'obiettivo "makefile.auto".  Arresto.

## [OK]easyhttp

## \- Complete -

step@Mike:~/workspace/Archive/ubuntu-it/repository/vbextreme/EasyFramework$ sudo ./cleanize 
rm -rf ./oobj/_.o
rm -rf ./libeasyalloc.so
rm -rf ./oobj/_.o
rm -rf ./libeasybenchmark.so
rm -rf ./oobj/_.o
rm -rf ./libeasyconsole.so
rm -rf ./oobj/_.o
rm -rf ./libeasycrypto.so
rm -rf ./oobj/_.o
rm -rf ./libeasyfile.so
rm -rf ./oobj/_.o
rm -rf ./libeasylist.so
rm -rf ./oobj/_.o
rm -rf ./libeasymath.so
rm -rf ./oobj/_.o
rm -rf ./libeasyserial.so
rm -rf ./oobj/_.o
rm -rf ./libeasystring.so
rm -rf ./oobj/_.o
rm -rf ./libeasythread.so
make: makefile.auto: File o directory non esistente
make: **\*  Nessuna regola per generare l'obiettivo "makefile.auto".  Arresto.
step@Mike:~/workspace/Archive/ubuntu-it/repository/vbextreme/EasyFramework$ ./generate 
[OK]gcc
[OK]make
[OK]stdio.h
[OK]stdlib.h
[OK]string.h
[OK]memory.h
[OK]unistd.h
[OK]fcntl.h
[OK]ioctl.h
[OK]sched.h
[OK]malloc.h
[OK]time.h
[OK]resource.h
[OK]errno.h
[OK]input.h
[OK]termios.h
[OK]types.h
[OK]stat.h
[OK]time.h
[OK]dirent.h
[OK]utime.h
[OK]pwd.h
[ER]curl.h

## step@Mike:~/workspace/Archive/ubuntu-it/repository/vbextreme/EasyFramework$ sudo ./install

## \- Install Easy Framework -

[OK]easytype
cp ./libeasyalloc.so /usr/lib/libeasyalloc.so
cp: impossibile eseguire stat di "./libeasyalloc.so": File o directory non esistente
makefile.auto:60: set di istruzioni per l'obiettivo "libinstall" non riuscito
make: **\* [libinstall] Errore 1
[ER]easyalloc
'''

**Comment by vbextreme** [comment]
il nuovo framework richiede libcurl, una volta installata 
$ ./generate
se si ferma ancora con errori postali.
altrimenti
$ sudo ./install

**Comment by vbextreme** [comment]
provvedero ad ampliare i messaggi di installazione in modo che siano più chiari e semplici possibili.
