### ISSUE TITLE
Problema al Ridimensionamento griglia terminale

### ISSUE THREAD

**Issue by GiovanniCardamone** [vbextreme/MagixCubic#2]
Quando la griglia del terminale viene ingrandita o rimpicciolita il gioco smette di funzionare come dovrebbe, in particolare la colorazione dei punti del terminale salta, colorando punti un po a caso.

**Comment by vbextreme** [comment]
il problema avviene perchè non viene intercettato il segnale del cambio dimensione, sarebbe da implementare.
Il gioco proseguirà dopo che avrò finito tutto il man dell'easy framework

**Comment by vbextreme** [comment]
Ho inziato ad intervenire sul problema, ora va meglio ma non viene centrato nello schermo confermi?

**Comment by GiovanniCardamone** [comment]
si, se non si rimpiccilisce la griglia tanto da impattare sulla casella di gioco la situazione rimane normale.

**Comment by vbextreme** [comment]
non avevo provato a rimpicciolire cosi tanto, grazie per la segnalazione e la conferma cercherò di risolvere
